--[[ Context table for configurator. initContext() returns shared ctx. initState() is an alias for compatibility. ]]

local function initContext()
  return {
    main = nil,
    mainSel = 1,
    selectConfigSelByContext = {},
    context = "ps2bbl",
    fileType = nil,
    currentPath = nil,
    lines = nil,
    chosenMcSlot = nil,
    state = "main",
    mcSel = 1,
    hddReady = false,
    prevPad = 0,
    optList = nil,
    optSel = 1,
    optScroll = 0,
    saveSplash = nil,
    editKey = nil,
    pathPickerSub = nil,
    pathPickerSel = 1,
    pathPickerScroll = 0,
    pathBrowsePath = nil,
    pathList = nil,
    isAddPath = false,
    addPathKey = nil,
    pathPickerContext = "osdmenu",
    pfs1Mounted = nil,
    colorOpt = nil,
    colorCh = 1,
    colorVals = nil,
    saveChoices = nil,
    saveSel = 1,
    entryList = {},
    entrySel = 1,
    entryScroll = 0,
    entryIdx = nil,
    entryEditSub = 1,
    pathPickerForEntryIdx = nil,
    pathPickerBblHotkeyKey = nil,
    pathPickerBblHotkeySlot = nil,
    pathPickerBblHotkeyDisabled = nil,
    textInputPrompt = nil,
    textInputValue = "",
    textInputMaxLen = 79,
    textInputCallback = nil,
    textInputGridSel = 1,
    textInputShift = false,
    editorCategoryIdx = 0,
    editorCategoryOptSelByFile = {},
    loadChoices = nil,
    loadSel = 1,
    entryPathSel = 1,
    entryPathScroll = 0,
    entryArgSel = 1,
    entryArgScroll = 0,
    bblHotkeySel = 1,
    bblHotkeyScroll = 0,
    bblHotkeyKey = nil,
    bblEntrySel = 1,
    bblEntryScroll = 0,
    bblEntryFocusSlot = nil,
    bblEntrySlot = nil,
    bblEntryDetailSel = 1,
    bblArgSel = 1,
    bblArgScroll = 0,
    cdromOptSel = 1,
    pathPickerEditIdx = nil,
    argEditIdx = nil,
    textInputReturnState = "menu_entry_edit",
    textInputCursor = 1,
    textInputScroll = 1,
    holdFrameCount = 0,
    configModified = false,
    editorLeavePrompt = nil,
    returnToSelectConfigAfterSave = nil,
    returnToSelectConfigAfterSaveFlash = nil,
  }
end

local function initState()
  return initContext()
end

return { initState = initState, initContext = initContext }
